version: '3'
services:
  app:
    build: .
    ports:
      - "5000:80"
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: network_db