apiVersion: v1
kind: Service
metadata:
  name: network-optimization-service
spec:
  selector:
    app: network-optimization
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer